# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-10 18:27
from __future__ import unicode_literals

import audit_log.models.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import proposal.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrantProposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_with_session_key', audit_log.models.fields.CreatingSessionKeyField(editable=False, max_length=40, null=True)),
                ('modified_with_session_key', audit_log.models.fields.LastSessionKeyField(editable=False, max_length=40, null=True)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_modified_datetime', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('title', models.CharField(error_messages={'blank': 'Title can not be empty.', 'max_length': 'Title must be less than 30 characters.', 'null': 'Title is a required field.'}, max_length=30, verbose_name='Title')),
                ('description', models.TextField(error_messages={'blank': 'Description can not be empty.', 'null': 'Description is a required field.'}, verbose_name='Description')),
                ('objective', models.TextField(error_messages={'blank': 'Objective can not be empty.', 'null': 'Objective is a required field.'}, verbose_name='Objective')),
                ('update', models.TextField(error_messages={'blank': 'Update can not be empty.', 'null': 'Update is a required field.'}, verbose_name='Update')),
                ('submit_datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('author', models.CharField(error_messages={'blank': 'Author Name can not be empty.', 'max_length': 'Author Name must be less than 100 characters.', 'null': 'Author Name is a required field.'}, max_length=100, verbose_name='Author Name')),
                ('created_by', audit_log.models.fields.CreatingUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_proposal_grantproposal_set', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('modified_by', audit_log.models.fields.LastUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_proposal_grantproposal_set', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
            ],
            options={
                'verbose_name_plural': 'GrantProposals',
                'verbose_name': 'GrantProposal',
            },
        ),
        migrations.CreateModel(
            name='ProgressReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_with_session_key', audit_log.models.fields.CreatingSessionKeyField(editable=False, max_length=40, null=True)),
                ('modified_with_session_key', audit_log.models.fields.LastSessionKeyField(editable=False, max_length=40, null=True)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_modified_datetime', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('attachment', models.FileField(upload_to=proposal.models.generate_progress_report_file, verbose_name='Progress Report')),
                ('created_by', audit_log.models.fields.CreatingUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_proposal_progressreport_set', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('grant_proposal', models.ForeignKey(error_messages={'blank': 'Grant Proposal can not be empty.', 'null': 'Grant Proposal is a required field.'}, on_delete=django.db.models.deletion.CASCADE, related_name='progress_reports', to='proposal.GrantProposal', verbose_name='Grant Proposal')),
                ('modified_by', audit_log.models.fields.LastUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_proposal_progressreport_set', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
            ],
            options={
                'verbose_name_plural': 'ProgressReports',
                'verbose_name': 'ProgressReport',
            },
        ),
        migrations.CreateModel(
            name='ProposalDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_with_session_key', audit_log.models.fields.CreatingSessionKeyField(editable=False, max_length=40, null=True)),
                ('modified_with_session_key', audit_log.models.fields.LastSessionKeyField(editable=False, max_length=40, null=True)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_modified_datetime', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('attachment', models.FileField(upload_to=proposal.models.generate_proposal_document_file, verbose_name='Proposal Document')),
                ('created_by', audit_log.models.fields.CreatingUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_proposal_proposaldocument_set', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('grant_proposal', models.ForeignKey(error_messages={'blank': 'Grant Proposal can not be empty.', 'null': 'Grant Proposal is a required field.'}, on_delete=django.db.models.deletion.CASCADE, related_name='proposal_documents', to='proposal.GrantProposal', verbose_name='Grant Proposal')),
                ('modified_by', audit_log.models.fields.LastUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_proposal_proposaldocument_set', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
            ],
            options={
                'verbose_name_plural': 'ProposalDocuments',
                'verbose_name': 'ProposalDocument',
            },
        ),
    ]
