# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-23 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0003_auto_20180214_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grantproposal',
            name='objective',
            field=models.TextField(error_messages={'blank': 'Objective can not be empty.'}, null=True, verbose_name='Objective'),
        ),
        migrations.AlterField(
            model_name='grantproposal',
            name='update',
            field=models.TextField(error_messages={'blank': 'Update can not be empty.'}, null=True, verbose_name='Update'),
        ),
    ]
