# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-10 18:27
from __future__ import unicode_literals

import audit_log.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_with_session_key', audit_log.models.fields.CreatingSessionKeyField(editable=False, max_length=40, null=True)),
                ('modified_with_session_key', audit_log.models.fields.LastSessionKeyField(editable=False, max_length=40, null=True)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_modified_datetime', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('city', models.CharField(error_messages={'blank': 'City can not be empty.', 'max_length': 'City must be less than 30 characters.', 'null': 'City is a required field.'}, max_length=30, verbose_name='City')),
                ('street', models.CharField(error_messages={'blank': 'Street can not be empty.', 'max_length': 'Street must be less than 30 characters.', 'null': 'Street is a required field.'}, max_length=30, verbose_name='Street')),
                ('room', models.CharField(error_messages={'blank': 'Room can not be empty.', 'max_length': 'Room must be less than 30 characters.', 'null': 'Room is a required field.'}, max_length=30, verbose_name='Room')),
                ('number', models.CharField(error_messages={'blank': 'Number can not be empty.', 'max_length': 'Number must be less than 30 characters.', 'null': 'Number is a required field.'}, max_length=30, verbose_name='Number')),
            ],
            options={
                'verbose_name_plural': 'Locations',
                'verbose_name': 'Location',
            },
        ),
    ]
