# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-03 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_auto_20180323_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, error_messages={'max_length': 'City must be less than 30 characters.'}, max_length=30, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='location',
            name='number',
            field=models.CharField(blank=True, error_messages={'max_length': 'Number must be less than 30 characters.'}, max_length=30, null=True, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='location',
            name='room',
            field=models.CharField(blank=True, error_messages={'max_length': 'Room must be less than 30 characters.'}, max_length=30, null=True, verbose_name='Room'),
        ),
        migrations.AlterField(
            model_name='location',
            name='street',
            field=models.CharField(blank=True, error_messages={'max_length': 'Street must be less than 30 characters.'}, max_length=30, null=True, verbose_name='Street'),
        ),
    ]
