# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-10 18:27
from __future__ import unicode_literals

import audit_log.models.fields
import datetime
from django.db import migrations, models
import equipment.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_with_session_key', audit_log.models.fields.CreatingSessionKeyField(editable=False, max_length=40, null=True)),
                ('modified_with_session_key', audit_log.models.fields.LastSessionKeyField(editable=False, max_length=40, null=True)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_modified_datetime', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('name', models.CharField(error_messages={'blank': 'Name can not be empty.', 'max_length': 'Name must be less than 255 characters.', 'null': 'Name is a required field.'}, max_length=255, verbose_name='Name')),
                ('company', models.CharField(error_messages={'blank': 'Company can not be empty.', 'max_length': 'Company must be less than 255 characters.', 'null': 'Company is a required field.'}, max_length=255, verbose_name='Company')),
                ('address', models.CharField(error_messages={'blank': 'Address can not be empty.', 'max_length': 'Address must be less than 255 characters.', 'null': 'Address is a required field.'}, max_length=255, verbose_name='Address')),
                ('description', models.TextField(error_messages={'blank': 'Description can not be empty.', 'null': 'Description is a required field.'}, verbose_name='Description')),
                ('cost', models.IntegerField(error_messages={'blank': 'Cost can not be empty.', 'null': 'Cost is a required field.'}, verbose_name='Cost')),
                ('contact_person', models.CharField(error_messages={'blank': 'Contact Person can not be empty.', 'max_length': 'Contact Person must be less than 255 characters.', 'null': 'Contact Person is a required field.'}, max_length=255, verbose_name='Contact Person')),
                ('receive_datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('start_datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('end_datetime', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': 'Equipments',
                'verbose_name': 'Equipment',
            },
        ),
        migrations.CreateModel(
            name='EquipmentDataSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_with_session_key', audit_log.models.fields.CreatingSessionKeyField(editable=False, max_length=40, null=True)),
                ('modified_with_session_key', audit_log.models.fields.LastSessionKeyField(editable=False, max_length=40, null=True)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_modified_datetime', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('attachment', models.FileField(upload_to=equipment.models.generate_data_sheet_file, verbose_name='Equipment Data Sheet')),
            ],
            options={
                'verbose_name_plural': 'DataSheets',
                'verbose_name': 'DataSheet',
            },
        ),
        migrations.CreateModel(
            name='EquipmentDocumentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_with_session_key', audit_log.models.fields.CreatingSessionKeyField(editable=False, max_length=40, null=True)),
                ('modified_with_session_key', audit_log.models.fields.LastSessionKeyField(editable=False, max_length=40, null=True)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_modified_datetime', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('attachment', models.FileField(upload_to=equipment.models.generate_documentation_file, verbose_name='Equipment Docummentation')),
            ],
            options={
                'verbose_name_plural': 'Documentations',
                'verbose_name': 'Documentation',
            },
        ),
        migrations.CreateModel(
            name='EquipmentFinancialDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_with_session_key', audit_log.models.fields.CreatingSessionKeyField(editable=False, max_length=40, null=True)),
                ('modified_with_session_key', audit_log.models.fields.LastSessionKeyField(editable=False, max_length=40, null=True)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_modified_datetime', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('attachment', models.FileField(upload_to=equipment.models.generate_financial_document_file, verbose_name='Equipment Financial Document')),
            ],
            options={
                'verbose_name_plural': 'FinancialDocuments',
                'verbose_name': 'FinancialDocument',
            },
        ),
        migrations.CreateModel(
            name='EquipmentLiciense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_with_session_key', audit_log.models.fields.CreatingSessionKeyField(editable=False, max_length=40, null=True)),
                ('modified_with_session_key', audit_log.models.fields.LastSessionKeyField(editable=False, max_length=40, null=True)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_modified_datetime', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('attachment', models.FileField(upload_to=equipment.models.generate_license_file, verbose_name='Equipment License')),
            ],
            options={
                'verbose_name_plural': 'Licienses',
                'verbose_name': 'Liciense',
            },
        ),
        migrations.CreateModel(
            name='EquipmentMaintenanceDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_with_session_key', audit_log.models.fields.CreatingSessionKeyField(editable=False, max_length=40, null=True)),
                ('modified_with_session_key', audit_log.models.fields.LastSessionKeyField(editable=False, max_length=40, null=True)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_modified_datetime', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('attachment', models.FileField(upload_to=equipment.models.generate_maintenance_doc_file, verbose_name='Equipment Maintenance Document')),
            ],
            options={
                'verbose_name_plural': 'MaintenanceDocuments',
                'verbose_name': 'MaintenanceDocument',
            },
        ),
        migrations.CreateModel(
            name='EquipmentManual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_with_session_key', audit_log.models.fields.CreatingSessionKeyField(editable=False, max_length=40, null=True)),
                ('modified_with_session_key', audit_log.models.fields.LastSessionKeyField(editable=False, max_length=40, null=True)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_modified_datetime', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('attachment', models.FileField(upload_to=equipment.models.generate_manual_file, verbose_name='Equipment Manual')),
            ],
            options={
                'verbose_name_plural': 'Manuals',
                'verbose_name': 'Manual',
            },
        ),
        migrations.CreateModel(
            name='EquipmentQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_with_session_key', audit_log.models.fields.CreatingSessionKeyField(editable=False, max_length=40, null=True)),
                ('modified_with_session_key', audit_log.models.fields.LastSessionKeyField(editable=False, max_length=40, null=True)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_modified_datetime', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('attachment', models.FileField(upload_to=equipment.models.generate_quote_file, verbose_name='Equipment Quote File')),
            ],
            options={
                'verbose_name_plural': 'Quotes',
                'verbose_name': 'Quote',
            },
        ),
        migrations.CreateModel(
            name='EquipmentReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_with_session_key', audit_log.models.fields.CreatingSessionKeyField(editable=False, max_length=40, null=True)),
                ('modified_with_session_key', audit_log.models.fields.LastSessionKeyField(editable=False, max_length=40, null=True)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_modified_datetime', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('attachment', models.FileField(upload_to=equipment.models.generate_receipt_file, verbose_name='Equipment Receipt')),
            ],
            options={
                'verbose_name_plural': 'Receipts',
                'verbose_name': 'Receipt',
            },
        ),
    ]
