# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-10 18:27
from __future__ import unicode_literals

import audit_log.models.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentreceipt',
            name='created_by',
            field=audit_log.models.fields.CreatingUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_equipment_equipmentreceipt_set', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='equipmentreceipt',
            name='equipment',
            field=models.ForeignKey(error_messages={'blank': 'Equipment can not be empty.', 'null': 'Equipment is a required field.'}, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_receipts', to='equipment.Equipment', verbose_name='Equipment'),
        ),
        migrations.AddField(
            model_name='equipmentreceipt',
            name='modified_by',
            field=audit_log.models.fields.LastUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_equipment_equipmentreceipt_set', to=settings.AUTH_USER_MODEL, verbose_name='modified by'),
        ),
        migrations.AddField(
            model_name='equipmentquote',
            name='created_by',
            field=audit_log.models.fields.CreatingUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_equipment_equipmentquote_set', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='equipmentquote',
            name='equipment',
            field=models.ForeignKey(error_messages={'blank': 'Equipment can not be empty.', 'null': 'Equipment is a required field.'}, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_quotes', to='equipment.Equipment', verbose_name='Equipment'),
        ),
        migrations.AddField(
            model_name='equipmentquote',
            name='modified_by',
            field=audit_log.models.fields.LastUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_equipment_equipmentquote_set', to=settings.AUTH_USER_MODEL, verbose_name='modified by'),
        ),
        migrations.AddField(
            model_name='equipmentmanual',
            name='created_by',
            field=audit_log.models.fields.CreatingUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_equipment_equipmentmanual_set', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='equipmentmanual',
            name='equipment',
            field=models.ForeignKey(error_messages={'blank': 'Equipment can not be empty.', 'null': 'Equipment is a required field.'}, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_mannuals', to='equipment.Equipment', verbose_name='Equipment'),
        ),
        migrations.AddField(
            model_name='equipmentmanual',
            name='modified_by',
            field=audit_log.models.fields.LastUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_equipment_equipmentmanual_set', to=settings.AUTH_USER_MODEL, verbose_name='modified by'),
        ),
        migrations.AddField(
            model_name='equipmentmaintenancedocument',
            name='created_by',
            field=audit_log.models.fields.CreatingUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_equipment_equipmentmaintenancedocument_set', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='equipmentmaintenancedocument',
            name='equipment',
            field=models.ForeignKey(error_messages={'blank': 'Equipment can not be empty.', 'null': 'Equipment is a required field.'}, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_maintenance_docs', to='equipment.Equipment', verbose_name='Equipment'),
        ),
        migrations.AddField(
            model_name='equipmentmaintenancedocument',
            name='modified_by',
            field=audit_log.models.fields.LastUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_equipment_equipmentmaintenancedocument_set', to=settings.AUTH_USER_MODEL, verbose_name='modified by'),
        ),
        migrations.AddField(
            model_name='equipmentliciense',
            name='created_by',
            field=audit_log.models.fields.CreatingUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_equipment_equipmentliciense_set', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='equipmentliciense',
            name='equipment',
            field=models.ForeignKey(error_messages={'blank': 'Equipment can not be empty.', 'null': 'Equipment is a required field.'}, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_licenses', to='equipment.Equipment', verbose_name='Equipment'),
        ),
        migrations.AddField(
            model_name='equipmentliciense',
            name='modified_by',
            field=audit_log.models.fields.LastUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_equipment_equipmentliciense_set', to=settings.AUTH_USER_MODEL, verbose_name='modified by'),
        ),
        migrations.AddField(
            model_name='equipmentfinancialdocument',
            name='created_by',
            field=audit_log.models.fields.CreatingUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_equipment_equipmentfinancialdocument_set', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='equipmentfinancialdocument',
            name='equipment',
            field=models.ForeignKey(error_messages={'blank': 'Equipment can not be empty.', 'null': 'Equipment is a required field.'}, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_financial_documents', to='equipment.Equipment', verbose_name='Equipment'),
        ),
        migrations.AddField(
            model_name='equipmentfinancialdocument',
            name='modified_by',
            field=audit_log.models.fields.LastUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_equipment_equipmentfinancialdocument_set', to=settings.AUTH_USER_MODEL, verbose_name='modified by'),
        ),
        migrations.AddField(
            model_name='equipmentdocumentation',
            name='created_by',
            field=audit_log.models.fields.CreatingUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_equipment_equipmentdocumentation_set', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='equipmentdocumentation',
            name='equipment',
            field=models.ForeignKey(error_messages={'blank': 'Equipment can not be empty.', 'null': 'Equipment is a required field.'}, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_documentations', to='equipment.Equipment', verbose_name='Equipment'),
        ),
        migrations.AddField(
            model_name='equipmentdocumentation',
            name='modified_by',
            field=audit_log.models.fields.LastUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_equipment_equipmentdocumentation_set', to=settings.AUTH_USER_MODEL, verbose_name='modified by'),
        ),
        migrations.AddField(
            model_name='equipmentdatasheet',
            name='created_by',
            field=audit_log.models.fields.CreatingUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_equipment_equipmentdatasheet_set', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='equipmentdatasheet',
            name='equipment',
            field=models.ForeignKey(error_messages={'blank': 'Equipment can not be empty.', 'null': 'Equipment is a required field.'}, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_data_sheets', to='equipment.Equipment', verbose_name='Equipment'),
        ),
        migrations.AddField(
            model_name='equipmentdatasheet',
            name='modified_by',
            field=audit_log.models.fields.LastUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_equipment_equipmentdatasheet_set', to=settings.AUTH_USER_MODEL, verbose_name='modified by'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='created_by',
            field=audit_log.models.fields.CreatingUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_equipment_equipment_set', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='modified_by',
            field=audit_log.models.fields.LastUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_equipment_equipment_set', to=settings.AUTH_USER_MODEL, verbose_name='modified by'),
        ),
    ]
