# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-31 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20180323_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='username',
            field=models.CharField(error_messages={'blank': 'Username can not be empty.', 'max_length': 'Username must be less than 30 characters.', 'null': 'Username is a required field.', 'unique': 'This Username has already been registered.'}, max_length=30, unique=True),
        ),
    ]
