# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-03 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_auto_20180331_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='full_name',
            field=models.CharField(blank=True, error_messages={'max_length': 'Full Name must be less than 30 characters.'}, max_length=30, null=True, verbose_name='Full Name'),
        ),
    ]
