# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-10 18:27
from __future__ import unicode_literals

import audit_log.models.fields
import datetime
from django.db import migrations, models
import event.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_with_session_key', audit_log.models.fields.CreatingSessionKeyField(editable=False, max_length=40, null=True)),
                ('modified_with_session_key', audit_log.models.fields.LastSessionKeyField(editable=False, max_length=40, null=True)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_modified_datetime', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('title', models.CharField(error_messages={'blank': 'Title can not be empty.', 'max_length': 'Title must be less than 255 characters.', 'null': 'Title is a required field.'}, max_length=255, verbose_name='Title')),
                ('description', models.TextField(error_messages={'blank': 'description can not be empty.', 'null': 'description is a required field.'}, verbose_name='Description')),
                ('start_datetime', models.DateTimeField(default=datetime.datetime.now, error_messages={'blank': 'Start Date can not be empty.', 'null': 'Start Date is a required field.'}, verbose_name='Start Date')),
                ('end_datetime', models.DateTimeField(default=datetime.datetime.now, error_messages={'blank': 'End Date can not be empty.', 'null': 'End Date is a required field.'}, verbose_name='End Date')),
            ],
            options={
                'verbose_name_plural': 'Events',
                'verbose_name': 'Event',
            },
        ),
        migrations.CreateModel(
            name='EventDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_with_session_key', audit_log.models.fields.CreatingSessionKeyField(editable=False, max_length=40, null=True)),
                ('modified_with_session_key', audit_log.models.fields.LastSessionKeyField(editable=False, max_length=40, null=True)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_modified_datetime', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('attachment', models.FileField(upload_to=event.models.generate_document_file, verbose_name='Event Document')),
            ],
            options={
                'verbose_name_plural': 'EventDocuments',
                'verbose_name': 'EventDocument',
            },
        ),
        migrations.CreateModel(
            name='EventMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_with_session_key', audit_log.models.fields.CreatingSessionKeyField(editable=False, max_length=40, null=True)),
                ('modified_with_session_key', audit_log.models.fields.LastSessionKeyField(editable=False, max_length=40, null=True)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_modified_datetime', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
            ],
            options={
                'verbose_name_plural': 'EventMembers',
                'verbose_name': 'EventMember',
            },
        ),
        migrations.CreateModel(
            name='EventPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_with_session_key', audit_log.models.fields.CreatingSessionKeyField(editable=False, max_length=40, null=True)),
                ('modified_with_session_key', audit_log.models.fields.LastSessionKeyField(editable=False, max_length=40, null=True)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_modified_datetime', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('attachment', models.ImageField(upload_to=event.models.generate_event_photo, verbose_name='Event Photo')),
            ],
            options={
                'verbose_name_plural': 'EventPhotos',
                'verbose_name': 'EventPhoto',
            },
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_with_session_key', audit_log.models.fields.CreatingSessionKeyField(editable=False, max_length=40, null=True)),
                ('modified_with_session_key', audit_log.models.fields.LastSessionKeyField(editable=False, max_length=40, null=True)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_modified_datetime', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('name', models.CharField(error_messages={'blank': 'Name can not be empty.', 'max_length': 'Name must be less than 255 characters.', 'null': 'Name is a required field.'}, max_length=255, verbose_name='Name')),
                ('identifier', models.CharField(error_messages={'blank': 'Identfier can not be empty.', 'max_length': 'Identfier must be less than 30 characters.', 'null': 'Identfier is a required field.'}, max_length=30, verbose_name='Identfier')),
            ],
            options={
                'verbose_name_plural': 'EventTypes',
                'verbose_name': 'EventType',
            },
        ),
    ]
