# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-10 18:27
from __future__ import unicode_literals

import audit_log.models.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='created_by',
            field=audit_log.models.fields.CreatingUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_event_eventtype_set', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='modified_by',
            field=audit_log.models.fields.LastUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_event_eventtype_set', to=settings.AUTH_USER_MODEL, verbose_name='modified by'),
        ),
        migrations.AddField(
            model_name='eventphoto',
            name='created_by',
            field=audit_log.models.fields.CreatingUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_event_eventphoto_set', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='eventphoto',
            name='event',
            field=models.ForeignKey(error_messages={'blank': 'Event can not be empty.', 'null': 'Event is a required field.'}, on_delete=django.db.models.deletion.CASCADE, to='event.Event', verbose_name='Event'),
        ),
        migrations.AddField(
            model_name='eventphoto',
            name='modified_by',
            field=audit_log.models.fields.LastUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_event_eventphoto_set', to=settings.AUTH_USER_MODEL, verbose_name='modified by'),
        ),
        migrations.AddField(
            model_name='eventmember',
            name='created_by',
            field=audit_log.models.fields.CreatingUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_event_eventmember_set', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='eventmember',
            name='event',
            field=models.ForeignKey(error_messages={'blank': 'Event can not be empty.', 'null': 'Event is a required field.'}, on_delete=django.db.models.deletion.CASCADE, related_name='event_members', to='event.Event'),
        ),
        migrations.AddField(
            model_name='eventmember',
            name='member',
            field=models.ForeignKey(error_messages={'blank': 'Member can not be empty.', 'null': 'Member is a required field.'}, on_delete=django.db.models.deletion.CASCADE, related_name='event_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventmember',
            name='modified_by',
            field=audit_log.models.fields.LastUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_event_eventmember_set', to=settings.AUTH_USER_MODEL, verbose_name='modified by'),
        ),
        migrations.AddField(
            model_name='eventdocument',
            name='created_by',
            field=audit_log.models.fields.CreatingUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_event_eventdocument_set', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='eventdocument',
            name='event',
            field=models.ForeignKey(error_messages={'blank': 'Event can not be empty.', 'null': 'Event is a required field.'}, on_delete=django.db.models.deletion.CASCADE, to='event.Event', verbose_name='Event'),
        ),
        migrations.AddField(
            model_name='eventdocument',
            name='modified_by',
            field=audit_log.models.fields.LastUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_event_eventdocument_set', to=settings.AUTH_USER_MODEL, verbose_name='modified by'),
        ),
        migrations.AddField(
            model_name='event',
            name='_type',
            field=models.ForeignKey(error_messages={'blank': 'EventType can not be empty.', 'null': 'EventType is a required field.'}, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='event.EventType'),
        ),
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=audit_log.models.fields.CreatingUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_event_event_set', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(error_messages={'blank': 'Location can not be empty.', 'null': 'Location is a required field.'}, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='location.Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='members',
            field=models.ManyToManyField(related_name='events', through='event.EventMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='modified_by',
            field=audit_log.models.fields.LastUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_event_event_set', to=settings.AUTH_USER_MODEL, verbose_name='modified by'),
        ),
    ]
