# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-10 18:27
from __future__ import unicode_literals

import audit_log.models.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_with_session_key', audit_log.models.fields.CreatingSessionKeyField(editable=False, max_length=40, null=True)),
                ('modified_with_session_key', audit_log.models.fields.LastSessionKeyField(editable=False, max_length=40, null=True)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_modified_datetime', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('title', models.CharField(error_messages={'blank': 'Title can not be empty.', 'max_length': 'Title must be less than 30 characters.', 'null': 'Title is a required field.'}, max_length=30, verbose_name='Title')),
                ('description', models.TextField(error_messages={'blank': 'Description can not be empty.', 'null': 'Description is a required field.'}, verbose_name='Description')),
                ('objective', models.TextField(error_messages={'blank': 'Objective can not be empty.', 'null': 'Objective is a required field.'}, verbose_name='Objective')),
                ('update', models.TextField(error_messages={'blank': 'Update can not be empty.', 'null': 'Update is a required field.'}, verbose_name='Update')),
                ('reference', models.TextField(error_messages={'blank': 'Reference can not be empty.', 'null': 'Reference is a required field.'}, verbose_name='Reference')),
                ('created_by', audit_log.models.fields.CreatingUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_project_idea_set', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('member', models.ForeignKey(error_messages={'blank': 'Member can not be empty.', 'null': 'Member is a required field.'}, on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to=settings.AUTH_USER_MODEL, verbose_name='Member')),
                ('modified_by', audit_log.models.fields.LastUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_project_idea_set', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
            ],
            options={
                'verbose_name_plural': 'Ideas',
                'verbose_name': 'Idea',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_with_session_key', audit_log.models.fields.CreatingSessionKeyField(editable=False, max_length=40, null=True)),
                ('modified_with_session_key', audit_log.models.fields.LastSessionKeyField(editable=False, max_length=40, null=True)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_modified_datetime', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('title', models.CharField(error_messages={'blank': 'Title can not be empty.', 'max_length': 'Title must be less than 30 characters.', 'null': 'Title is a required field.'}, max_length=30, verbose_name='Title')),
                ('description', models.TextField(error_messages={'blank': 'Description can not be empty.', 'null': 'Description is a required field.'}, verbose_name='Description')),
                ('objective', models.TextField(error_messages={'blank': 'Objective can not be empty.', 'null': 'Objective is a required field.'}, verbose_name='Objective')),
                ('update', models.TextField(error_messages={'blank': 'Update can not be empty.', 'null': 'Update is a required field.'}, verbose_name='Update')),
                ('start_datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('end_datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('created_by', audit_log.models.fields.CreatingUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_project_project_set', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('member', models.ForeignKey(error_messages={'blank': 'Member can not be empty.', 'null': 'Member is a required field.'}, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='Member')),
                ('modified_by', audit_log.models.fields.LastUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_project_project_set', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
            ],
            options={
                'verbose_name_plural': 'Projects',
                'verbose_name': 'Project',
            },
        ),
    ]
