# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-23 12:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='member',
            field=models.ForeignKey(error_messages={'blank': 'Member can not be empty.'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to=settings.AUTH_USER_MODEL, verbose_name='Member'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='objective',
            field=models.TextField(error_messages={'blank': 'Objective can not be empty.'}, null=True, verbose_name='Objective'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='reference',
            field=models.TextField(error_messages={'blank': 'Reference can not be empty.'}, null=True, verbose_name='Reference'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='update',
            field=models.TextField(error_messages={'blank': 'Update can not be empty.'}, null=True, verbose_name='Update'),
        ),
        migrations.AlterField(
            model_name='project',
            name='member',
            field=models.ForeignKey(error_messages={'blank': 'Member can not be empty.'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='Member'),
        ),
        migrations.AlterField(
            model_name='project',
            name='objective',
            field=models.TextField(error_messages={'blank': 'Objective can not be empty.'}, null=True, verbose_name='Objective'),
        ),
        migrations.AlterField(
            model_name='project',
            name='update',
            field=models.TextField(error_messages={'blank': 'Update can not be empty.'}, null=True, verbose_name='Update'),
        ),
    ]
