# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-03 10:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20180323_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to=settings.AUTH_USER_MODEL, verbose_name='Member'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='reference',
            field=models.TextField(blank=True, null=True, verbose_name='Reference'),
        ),
    ]
