# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-10 18:27
from __future__ import unicode_literals

import audit_log.models.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import publication.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_with_session_key', audit_log.models.fields.CreatingSessionKeyField(editable=False, max_length=40, null=True)),
                ('modified_with_session_key', audit_log.models.fields.LastSessionKeyField(editable=False, max_length=40, null=True)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_modified_datetime', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('title', models.CharField(error_messages={'blank': 'Title can not be empty.', 'max_length': 'Title must be less than 30 characters.', 'null': 'Title is a required field.'}, max_length=30, verbose_name='Title')),
                ('journal', models.TextField(error_messages={'blank': 'Journal can not be empty.', 'null': 'Journal is a required field.'}, verbose_name='Journal')),
                ('author', models.CharField(error_messages={'blank': 'Author can not be empty.', 'max_length': 'Author must be less than 100 characters.', 'null': 'Author is a required field.'}, max_length=100, verbose_name='Author')),
                ('book_title', models.CharField(error_messages={'blank': 'Book Title can not be empty.', 'max_length': 'Book Title must be less than 100 characters.', 'null': 'Book Title is a required field.'}, max_length=100, verbose_name='Book Title')),
                ('year', models.IntegerField(error_messages={'blank': 'Publication Year can not be empty.', 'null': 'Publication Year is a required field.'}, verbose_name='Publication Year')),
                ('volume', models.IntegerField(error_messages={'blank': 'Publication Volume can not be empty.', 'null': 'Publication Volume is a required field.'}, verbose_name='Publication Volume')),
                ('number', models.IntegerField(error_messages={'blank': 'Publication Number can not be empty.', 'null': 'Publication Number is a required field.'}, verbose_name='Publication Number')),
                ('start_page', models.IntegerField(error_messages={'blank': 'Start Page can not be empty.', 'null': 'Start Page is a required field.'}, verbose_name='Start Page')),
                ('end_page', models.IntegerField(error_messages={'blank': 'End Page can not be empty.', 'null': 'End Page is a required field.'}, verbose_name='End Page')),
                ('publisher', models.CharField(error_messages={'blank': 'Publisher can not be empty.', 'max_length': 'Publisher must be less than 100 characters.', 'null': 'Publisher is a required field.'}, max_length=100, verbose_name='Publisher')),
                ('institution', models.CharField(error_messages={'blank': 'Institution can not be empty.', 'max_length': 'Institution must be less than 100 characters.', 'null': 'Institution is a required field.'}, max_length=100, verbose_name='Institution')),
                ('address', models.CharField(error_messages={'blank': 'Address can not be empty.', 'max_length': 'Address must be less than 255 characters.', 'null': 'Address is a required field.'}, max_length=255, verbose_name='Address')),
                ('note', models.TextField(error_messages={'blank': 'Note can not be empty.', 'null': 'Note is a required field.'}, verbose_name='Note')),
            ],
            options={
                'verbose_name_plural': 'Publications',
                'verbose_name': 'Publication',
            },
        ),
        migrations.CreateModel(
            name='PublicationFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_with_session_key', audit_log.models.fields.CreatingSessionKeyField(editable=False, max_length=40, null=True)),
                ('modified_with_session_key', audit_log.models.fields.LastSessionKeyField(editable=False, max_length=40, null=True)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_modified_datetime', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('attachment', models.FileField(upload_to=publication.models.generate_paper_file, verbose_name='Publication File')),
                ('created_by', audit_log.models.fields.CreatingUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_publication_publicationfile_set', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('modified_by', audit_log.models.fields.LastUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_publication_publicationfile_set', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
                ('publication', models.ForeignKey(error_messages={'blank': 'Publication can not be empty.', 'null': 'Publication is a required field.'}, on_delete=django.db.models.deletion.CASCADE, related_name='publication_files', to='publication.Publication', verbose_name='Publication')),
            ],
            options={
                'verbose_name_plural': 'PublicationFiles',
                'verbose_name': 'PublicationFile',
            },
        ),
        migrations.CreateModel(
            name='PublicationMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_with_session_key', audit_log.models.fields.CreatingSessionKeyField(editable=False, max_length=40, null=True)),
                ('modified_with_session_key', audit_log.models.fields.LastSessionKeyField(editable=False, max_length=40, null=True)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_modified_datetime', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('created_by', audit_log.models.fields.CreatingUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_publication_publicationmember_set', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('member', models.ForeignKey(error_messages={'blank': 'Member can not be empty.', 'null': 'Member is a required field.'}, on_delete=django.db.models.deletion.CASCADE, related_name='publication_members', to=settings.AUTH_USER_MODEL)),
                ('modified_by', audit_log.models.fields.LastUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_publication_publicationmember_set', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
                ('publication', models.ForeignKey(error_messages={'blank': 'Publication can not be empty.', 'null': 'Publication is a required field.'}, on_delete=django.db.models.deletion.CASCADE, related_name='publication_members', to='publication.Publication')),
            ],
            options={
                'verbose_name_plural': 'PublicationMembers',
                'verbose_name': 'PublicationMember',
            },
        ),
        migrations.CreateModel(
            name='PublicationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_with_session_key', audit_log.models.fields.CreatingSessionKeyField(editable=False, max_length=40, null=True)),
                ('modified_with_session_key', audit_log.models.fields.LastSessionKeyField(editable=False, max_length=40, null=True)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_modified_datetime', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('name', models.CharField(error_messages={'blank': 'Name can not be empty.', 'max_length': 'Name must be less than 255 characters.', 'null': 'Name is a required field.'}, max_length=255, verbose_name='Name')),
                ('identifier', models.CharField(error_messages={'blank': 'Identfier can not be empty.', 'max_length': 'Identfier must be less than 30 characters.', 'null': 'Identfier is a required field.'}, max_length=30, verbose_name='Identfier')),
                ('created_by', audit_log.models.fields.CreatingUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_publication_publicationtype_set', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('modified_by', audit_log.models.fields.LastUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_publication_publicationtype_set', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
            ],
            options={
                'verbose_name_plural': 'PublicationTypes',
                'verbose_name': 'PublicationType',
            },
        ),
        migrations.AddField(
            model_name='publication',
            name='_type',
            field=models.ForeignKey(error_messages={'blank': 'Publication Type can not be empty.', 'null': 'Publication Type is a required field.'}, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='publication.PublicationType'),
        ),
        migrations.AddField(
            model_name='publication',
            name='created_by',
            field=audit_log.models.fields.CreatingUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_publication_publication_set', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='publication',
            name='members',
            field=models.ManyToManyField(related_name='publications', through='publication.PublicationMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publication',
            name='modified_by',
            field=audit_log.models.fields.LastUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_publication_publication_set', to=settings.AUTH_USER_MODEL, verbose_name='modified by'),
        ),
    ]
