# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-31 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0003_auto_20180323_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='abstract',
            field=models.TextField(blank=True, null=True, verbose_name='Paper Abstract'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='address',
            field=models.CharField(blank=True, error_messages={'max_length': 'Address must be less than 255 characters.'}, max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='book_title',
            field=models.CharField(blank=True, error_messages={'max_length': 'Book Title must be less than 100 characters.'}, max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='end_page',
            field=models.IntegerField(blank=True, null=True, verbose_name='End Page'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='institution',
            field=models.CharField(blank=True, error_messages={'max_length': 'Institution must be less than 100 characters.'}, max_length=100, null=True, verbose_name='Institution'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Publication Number'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publisher',
            field=models.CharField(blank=True, error_messages={'max_length': 'Publisher must be less than 100 characters.'}, max_length=100, null=True, verbose_name='Publisher'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='start_page',
            field=models.IntegerField(blank=True, null=True, verbose_name='Start Page'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='volume',
            field=models.IntegerField(blank=True, null=True, verbose_name='Publication Volume'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Publication Year'),
        ),
    ]
