# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-31 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0004_auto_20180331_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='publication.PublicationType'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(error_messages={'blank': 'Title can not be empty.', 'max_length': 'Title must be less than 30 characters.', 'null': 'Title is a required field.'}, max_length=500, verbose_name='Title'),
        ),
    ]
