# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-31 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0005_auto_20180331_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Note'),
        ),
    ]
