# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-31 14:00
from __future__ import unicode_literals

import audit_log.models.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publication', '0006_auto_20180331_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_with_session_key', audit_log.models.fields.CreatingSessionKeyField(editable=False, max_length=40, null=True)),
                ('modified_with_session_key', audit_log.models.fields.LastSessionKeyField(editable=False, max_length=40, null=True)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_modified_datetime', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('name', models.CharField(error_messages={'blank': 'Username can not be empty.', 'max_length': 'Username must be less than 30 characters.', 'null': 'Username is a required field.', 'unique': 'This Username has already been registered.'}, max_length=100, unique=True)),
                ('created_by', audit_log.models.fields.CreatingUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_publication_publicationauthor_set', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('modified_by', audit_log.models.fields.LastUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_publication_publicationauthor_set', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
            ],
            options={
                'verbose_name_plural': 'PublicationAuthors',
                'verbose_name': 'PublicationAuthor',
            },
        ),
        migrations.RemoveField(
            model_name='publication',
            name='members',
        ),
        migrations.AlterField(
            model_name='publication',
            name='authors',
            field=models.ManyToManyField(blank=True, to='publication.PublicationAuthor', verbose_name='Authors'),
        ),
    ]
